2023-07-10 17:34:08,793 - INFO - Loading features from data\train_features.csv and data\test_features.csv
2023-07-10 17:34:08,986 - INFO - Training models with features with config ModelTrainerConfig(k_features_grid=[10, 20, 40, 'all'], feature_selection_score_function=<function mutual_info_classif at 0x00000135BDCF5280>, models=[Model(model_name=Logistic Regression, model_parameter_grid={'C': [0.1, 0.5, 1.0, 2.0, 5.0], 'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'], 'max_iter': [200, 500, 1000], 'n_jobs': [-1], 'random_state': [42]}, model=LogisticRegression()), Model(model_name=Random Forest, model_parameter_grid={'n_estimators': [100, 200, 500, 1000], 'criterion': ['gini', 'entropy', 'log_loss'], 'max_depth': [None, 10, 20, 50, 100]}, model=RandomForestClassifier()), Model(model_name=KNN, model_parameter_grid={'n_neighbors': [3, 5, 7, 9, 11, 13, 15], 'weights': ['distance'], 'p': [1, 2], 'n_jobs': [-1]}, model=KNeighborsClassifier()), Model(model_name=SVM, model_parameter_grid={'C': [0.1, 0.5, 1.0, 2.0, 5.0], 'kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'degree': [1, 2, 3, 4, 5], 'gamma': ['scale', 'auto'], 'max_iter': [200, 500, 1000], 'random_state': [42]}, model=SVC()), Model(model_name=Decision Tree, model_parameter_grid={'criterion': ['gini', 'entropy'], 'splitter': ['best'], 'max_depth': [None, 5, 10, 50, 100], 'random_state': [42]}, model=DecisionTreeClassifier())], target_column=label, score_criteria=f1_micro, cv=5)
2023-07-10 17:37:20,572 - ERROR - exception calling callback for <Future at 0x135c49c6f70 state=finished raised TerminatedWorkerError>
Traceback (most recent call last):
  File "F:\AlexisF\python\lib\site-packages\joblib\externals\loky\_base.py", line 26, in _invoke_callbacks
    callback(self)
  File "F:\AlexisF\python\lib\site-packages\joblib\parallel.py", line 385, in __call__
    self.parallel.dispatch_next()
  File "F:\AlexisF\python\lib\site-packages\joblib\parallel.py", line 834, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "F:\AlexisF\python\lib\site-packages\joblib\parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "F:\AlexisF\python\lib\site-packages\joblib\parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "F:\AlexisF\python\lib\site-packages\joblib\_parallel_backends.py", line 556, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "F:\AlexisF\python\lib\site-packages\joblib\externals\loky\reusable_executor.py", line 176, in submit
    return super().submit(fn, *args, **kwargs)
  File "F:\AlexisF\python\lib\site-packages\joblib\externals\loky\process_executor.py", line 1129, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

